spring.application.name=tripmate

# Server Configuration
server.port=8081

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tripmate
spring.datasource.username=postgres
spring.datasource.password=ade
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false
